Gemfile.lock, app/jobs/import/chordpro.rb, app/jobs/import/ozbcoz.rb, app/models/songsheet.rb, app/models/track.rb, lib/tasks/data.rake, test/jobs/import/ozbcoz_test.rb, test/models/songsheet_test.rb, test/vcr/ozbcoz.yml
This tries to clean up the data to match more of the imported songsheets to known tracks
Running this on production associated 740 songsheets with tracks. There's still 1558 to go which will likely require manual intervention or better matching (e.g. "Everly Brothers" => "The Everly Brothers")
=> Data cleanup

app/frontend/index.html, app/frontend/manifest.json, vite.config.js
Fix warnings in Chrome about the manifest
cc #112
=> Fix manifest warnings

app/frontend/router/index.js, app/frontend/tailwind.config.js, app/frontend/views/App.vue, app/frontend/views/ArtistListView.vue, app/frontend/views/DiscoverView.vue, app/frontend/views/LibraryView.vue, app/frontend/views/SetlistListView.vue, app/frontend/views/SongsheetListView.vue, app/frontend/views/TabsView.vue
Show library list on library tab on phone, show in sidebar on larger screens.
=> Fix library tab on phones

app/frontend/application.css, app/frontend/components/AlbumItem.vue, app/frontend/components/SongSheet.vue, app/frontend/components/SongsheetMedia.vue, app/frontend/components/SongsheetSettingsModal.vue, app/frontend/components/YoutubeEmbed.vue, app/frontend/icons.js, app/frontend/views/SongsheetView.vue, app/models/artist_work.rb, app/models/medium.rb, app/models/songsheet.rb, app/models/track.rb, app/views/api/songsheets/show.json.jbuilder, capacitor.config.json, db/migrate/20220513151136_create_media.rb, db/structure.sql, ios/App/App/capacitor.config.json, lib/tasks/data.rake, package.json, test/controllers/api/songsheets_controller_test.rb, test/factories.rb, test/models/songsheet_test.rb, test/models/track_test.rb, yarn.lock
Eventually this same model will be used to link to other media (Spotify, Apple Music, etc), but showing YouTube videos along side the song is already super useful.
=> Show YouTube videos

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/artist.rb, app/models/artist_work.rb, app/models/genre.rb, app/models/medium.rb, app/models/setlist.rb, app/models/setlist_item.rb, app/models/songsheet.rb, app/models/track.rb, db/migrate/20220514222125_create_versions.rb, db/migrate/20220514222126_add_object_changes_to_versions.rb, db/structure.sql
Track changes to models with paper trail gem
=> Add paper trail

.github/workflows/tests.yml, Gemfile, Gemfile.lock, app/controllers/api/users_controller.rb, app/jobs/performable_method.rb, app/mailers/application_mailer.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/user_mailer/welcome.html.erb, config/application.rb, config/initializers/good_job.rb, config/initializers/mailkick.rb, db/migrate/20220614211748_create_mailkick_subscriptions.rb, db/structure.sql, test/controllers/api/users_controller_test.rb, test/mailers/previews/user_mailer_preview.rb, test/mailers/user_mailer_test.rb
This adds a simple welcome email, and [mailkick](https://github.com/ankane/mailkick) to manage subscriptions
=> Welcome email

app/frontend/components.js, app/frontend/components/AlbumItem.vue, app/frontend/components/ShareItem.vue, app/frontend/components/SongsheetItem.vue, app/frontend/components/TrackItem.vue, app/frontend/icons.js, app/frontend/views/SetlistDetailView.vue, app/frontend/views/SongsheetView.vue, package.json, yarn.lock
=> Add share links to context menus

app/controllers/sitemaps_controller.rb, app/frontend/public/robots.txt, app/models/concerns/metadata.rb, app/views/sitemaps/index.xml.builder, app/views/sitemaps/show.xml.builder, app/views/user_mailer/forgot_password.html.erb, config/application.rb, config/routes.rb, test/controllers/sitemaps_controller_test.rb
=> Add Sitemap

Gemfile, Gemfile.lock, app/controllers/api/authenticate_controller.rb, app/controllers/api/songsheets_controller.rb, app/controllers/api/users_controller.rb, app/models/ahoy/event.rb, app/models/ahoy/visit.rb, config/initializers/ahoy.rb, db/migrate/20220618131530_create_ahoy_visits_and_events.rb, db/structure.sql
https://github.com/ankane/ahoy
=> Add ahoy for basic analytics

Gemfile, Gemfile.lock, config/initializers/motor.rb, config/routes.rb, db/migrate/20220619124827_install_motor_admin.rb, db/structure.sql
https://github.com/motor-admin/motor-admin-rails
=> Add motor admin

app/frontend/components/SongsheetMedia.vue, app/frontend/components/YoutubeEmbed.vue, app/frontend/views/SongsheetEditorView.vue, app/models/medium.rb, app/models/songsheet.rb, app/models/track.rb, app/views/api/songsheets/show.json.jbuilder, db/migrate/20220627025626_drop_media.rb, db/structure.sql, lib/tasks/data.rake, test/controllers/api/songsheets_controller_test.rb, test/factories.rb, test/models/songsheet_test.rb, test/models/track_test.rb
Fixes #335 by using `{meta: media https://youtube.com/…}` for external media links.
=> Use meta tag in source to define media

app/controllers/api/discover_controller.rb, app/jobs/generated_setlists.rb, app/models/user.rb, app/views/api/discover/show.json.jbuilder, client/src/views/DiscoverView.vue, client/src/views/GenreListView.vue, config/initializers/good_job.rb, config/routes.rb, test/controllers/api/discover_controller_test.rb, test/jobs/generated_setlists_test.rb
Adds generated setlists that are updated every day.
Fixes #297
=> Generated setlists

Brewfile, Gemfile, Gemfile.lock, app/controllers/api/search_controller.rb, app/controllers/api_controller.rb, app/helpers/application_helper.rb, app/jobs/download_attachment.rb, app/jobs/update_listener_counts.rb, app/models/album.rb, app/models/artist.rb, app/models/concerns/metadata.rb, app/models/genre.rb, app/models/songsheet.rb, app/models/track.rb, app/views/api/albums/_album.json.jbuilder, app/views/api/artists/_artist.json.jbuilder, app/views/api/artists/show.json.jbuilder, app/views/api/genres/_genre.json.jbuilder, app/views/api/search/index.json.jbuilder, app/views/api/tracks/_track.json.jbuilder, config/environments/production.rb, config/initializers/activestorage.rb, config/storage.yml, db/migrate/20220711144650_create_active_storage_tables.active_storage.rb, db/schema.rb, render.yaml, test/models/album_test.rb
```
Artist.find_each {|a| a.download_image_from_metadata; a.download_banner_from_metadata } 
Album.find_each(&:download_image_from_metadata)
````
Fixes #331
=> Store artist/album images

Gemfile, Gemfile.lock, client/src/application.js, client/src/sentry.js, config/initializers/sentry.rb, package.json, yarn.lock
=> Use Sentry for error tracking

app/helpers/application_helper.rb, app/models/album.rb, app/models/artist.rb, app/models/concerns/metadata.rb, app/models/genre.rb, app/models/songsheet.rb, app/models/track.rb, app/views/api/albums/_album.json.jbuilder, app/views/api/artists/_artist.json.jbuilder, app/views/api/artists/show.json.jbuilder, app/views/api/genres/_genre.json.jbuilder, app/views/api/search/index.json.jbuilder, app/views/api/setlists/_setlist.json.jbuilder, app/views/api/tracks/_track.json.jbuilder, client/src/components/AlbumItem.vue, client/src/components/SetlistItem.vue, client/src/components/SongsheetItem.vue, client/src/components/TrackItem.vue, client/src/views/AlbumView.vue, client/src/views/SongsheetView.vue, db/migrate/20220719130756_remove_genre_thumbnail.rb, db/schema.rb
Define variants on each model to get reasonable sizes.
Return multiple variants in api response for album cover.
=> Update variant names and sizes

app/controllers/api/albums_controller.rb, app/controllers/api/artists_controller.rb, app/controllers/api/genres_controller.rb, app/controllers/api/home_controller.rb, app/controllers/api/setlists_controller.rb, app/controllers/api/songsheets_controller.rb, app/controllers/api/tracks_controller.rb, app/controllers/api_controller.rb, app/jobs/update_rank.rb, app/models/album.rb, app/models/artist.rb, app/models/concerns/viewable.rb, app/models/genre.rb, app/models/section.rb, app/models/setlist.rb, app/models/songsheet.rb, app/models/user.rb, app/views/api/home/show.json.jbuilder, client/src/views/HomeView.vue, db/migrate/20221226122025_convert_songsheet_plays_to_views.rb, db/schema.rb, test/factories.rb, test/jobs/update_rank_test.rb, test/models/concerns/viewable_test.rb, test/models/user_test.rb
Use recently viewed items to update home page
=> Track views, use for signed in home section

.gitignore, app/views/api/tracks/_track.json.jbuilder, client/src/client.js, client/src/components/AddToSetlistModal.vue, client/src/components/AlbumItem.vue, client/src/components/AppView.vue, client/src/components/DataSource.vue, client/src/components/ReloadPwa.vue, client/src/components/SongSheet.vue, client/src/components/SongsheetVersionsModal.vue, client/src/icons.js, client/src/router/routes.js, client/src/sentry.js, client/src/service_workers/offline.js, client/src/views/AlbumListView.vue, client/src/views/ArtistListView.vue, client/src/views/GenreListView.vue, client/src/views/HomeView.vue, client/src/views/SetlistDetailView.vue, client/src/views/SetlistListView.vue, client/src/views/SongsheetListView.vue, client/src/views/SongsheetView.vue, client/src/views/TrackListView.vue, client/src/views/TrackView.vue, package.json, vite.config.js, yarn.lock
=> Better offline support 

Gemfile, Gemfile.lock, app/controllers/api/flipper_controller.rb, client/src/components/ReloadPwa.vue, client/src/useFlipper.js, config/routes.rb, db/migrate/20230120144044_create_flipper_tables.rb, db/schema.rb, test/controllers/api/flipper_controller_test.rb, test/test_helper.rb
To make it easier to roll out and test unfinished features.
=> Add Flipper with API and simple JS client

Gemfile, Gemfile.lock, app/controllers/api/flipper_controller.rb, client/src/components/ReloadPwa.vue, client/src/useFlipper.js, config/routes.rb, db/migrate/20230120144044_create_flipper_tables.rb, db/schema.rb, test/controllers/api/flipper_controller_test.rb, test/test_helper.rb
Attempting to show a prompt to add app to home screen per [MDN's demo](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen), but doesn't seem to be working.
=> Prompt to install app

client/src/components/ChordDiagram.vue, client/src/components/SongSheet.vue, client/src/components/SongSheetChord.vue, package.json, yarn.lock
=> Use unicode modifier for #/b

client/src/components/Tuner.vue, client/src/components/TunerMeter.vue, client/src/components/TunerNote.vue, client/src/lib/tuner.js, client/src/stylesheets/variables.css, package.json, yarn.lock
Redesigned and improved tuner that uses exponential moving average over 250ms to smooth pitch detection
=> Tuner improvements

.github/workflows/tests.yml, client/src/components/AddToLibraryButton.vue, client/src/components/AlbumItem.vue, client/src/components/LibraryPlaceholder.vue, client/src/components/SetlistItem.vue, client/src/components/ShareItem.vue, client/src/components/SongsheetContent.vue, client/src/components/SongsheetMedia.vue, client/src/components/SongsheetParser.vue, client/src/components/SongsheetSettingsModal.vue, client/src/components/SongsheetVersionsModal.vue, client/src/components/TrackItem.vue, client/src/composables/index.js, client/src/composables/useSongsheetParser.js, client/src/views/PasswordResetView.vue, client/src/views/SongsheetEditorView.vue, client/test/components/SongsheetContent.vue.test.js, client/test/components/YoutubeEmbed.vue.test.js, package-lock.json, package.json, vite.config.js
Adds vitest to run JavaScript/Vue client tests.
=> Add client tests

app/models/duration.rb, app/models/songsheet.rb, app/views/api/songsheets/_songsheet.json.jbuilder, client/src/components/AutoScroll.vue, client/src/composables/index.js, client/src/composables/useAutoScroll.js, client/src/icons.js, client/src/stores/songsheet-settings.js, client/src/views/SongsheetView.vue, test/models/duration_test.rb, test/models/songsheet_test.rb
This adds an autoscroll feature when viewing sonsheets.
cc @edwinzap
=> Autoscroll

client/src/views/SongsheetView.vue, ios/App/App/config.xml, ios/App/Podfile, package-lock.json, package.json
The [WakeLock](https://developer.mozilla.org/en-US/docs/Web/API/WakeLock) API looks like it has much better browser support than it did ~2 years ago.
=> Keep screen awake using WakeLock API

client/src/application.css, client/src/application.js, client/src/components/AddToLibraryButton.vue, client/src/components/FullscreenButton.vue, client/src/components/InstrumentControl.vue, client/src/components/TransposeControl.vue, client/src/views/SongsheetView.vue, package-lock.json, package.json
=> Add tooltips on toolbar buttons

app/jobs/generated_setlists.rb, app/jobs/generated_setlists/decades.rb, app/jobs/generated_setlists/favorites.rb, app/jobs/generated_setlists/key_of.rb, app/jobs/generated_setlists/recently_updated.rb, app/jobs/generated_setlists/too_many_versions.rb, app/jobs/generated_setlists/trending.rb, app/jobs/generated_setlists/unmatched.rb, app/jobs/generated_setlists/whats_new.rb, app/models/search.rb, app/models/setlist.rb, client/src/views/DiscoverView.vue, test/factories.rb, test/jobs/generated_setlists_test.rb, test/models/search_test.rb
=> Generate setlists by key, add setlists to search

client/src/components/AddToSetlistModal.vue, client/src/components/NewSetlistModal.vue
The data was being passed as a string instead of parsed as JSON.
cc @mattgraham
=> Fix for adding a song to a new setlist

client/src/components/FontSizeControl.vue, client/src/components/SongsheetContent.vue, client/src/stores/index.js, client/src/stores/theme.js, client/src/views/SongsheetView.vue, client/tailwind.config.js
=> Add control to adjust font size

client/src/components/ColumnLayout.vue, client/src/components/SongsheetContent.vue, client/src/views/SongsheetView.vue
This updates the scrolling to try to snap to paragraphs/sections when scrolling manually, and extracts the column layout into its own component.
=> Snap to songsheet paragraphs

app/controllers/api/history_controller.rb, app/controllers/api/home_controller.rb, app/views/api/history/show.json.jbuilder, client/src/router/routes.js, client/src/views/SongsheetListView.vue, config/routes.rb
This adds link in "Recently Played" section on home page to full paginated history
=> Link recently played to full history

client/src/components/Editor.js, client/src/composables/useSongsheetParser.js, client/src/lib/detect_format.js, client/src/views/SongsheetEditorView.vue, client/test/composables/useSongsheetParser.test.js
1. Fixes issue where pasting clears entire document except for new text
2. Moves selection to end of paste
3. Fixes issue where pasting again would duplicate text
=> Better paste

app/controllers/api/authenticate_controller.rb, client/src/components/AppView.vue, client/src/components/ErrorMessage.vue, client/src/components/OfflineMessage.vue, client/src/sentry.js, client/src/stores/auth.js, client/src/views/UserSigninModal.vue, client/src/views/UserSignupModal.vue, package-lock.json, package.json, vite.config.js
Tweak some error handling code to try to get better error messages
=> Better errors

client/src/components/ChordSheet/Chord.vue, client/src/components/ChordSheet/ChordLyricsPair.vue, client/src/components/SongsheetContent.vue
ChordPro input:
```chordpro
[G]This is an awesome [*annotated]lyric
```
Rendered output:
Fixes #1390
=> Add support for annotations

client/src/components/KeyModal.vue
=> Dismiss key modal when pressing back button

client/src/components/KeyModal.vue
=> Add reset button to key modal

app/views/api/albums/show.json.jbuilder, app/views/api/tracks/show.json.jbuilder, db/migrate/20241017184151_remove_thaudiodb_metadata.rb, db/schema.rb, test/jobs/associate_songsheet_metadata_test.rb
=> Remove metadata column
